### ISSUE TITLE
setup does not work (for me)

### ISSUE THREAD

**Issue by MFJansen** [pymoc/pymoc_old#2]
While I can successfully use setup.py install, I don't seem to be able to access pymoc modules (without adding the corresponding path). I also must say that I don't understand the setup.py script - that is it is not clear to me why it should work. I'm admittedly not an expert though, so rather that re-writing it in my own way (potentially breaking other stuff), I thought I raise an issue. 

On a related note: I thought it is customary for the setup.py script to be in the main root directory of the package, no?

**Comment by mbueti** [comment]
That's odd...it looks like maybe there was a local caching issue that masked that setup problem for me.

Regardless, it SHOULD now be corrected. The setup has been simplified, and moved up to the base of the project (I'd tried isolating the python code into the src, but that makes less sense here).

Previously, I'd been explicitly enumerating the individual modules, which is an option for smaller python projects, but we should see more consistent results with this newer setup script.

For importing, I'm sub-modularized the package, so that we can keep utils, modules, and eventually the model interface compartmentalized for importing, documentation, etc. So, you should now be able to import the column model via `from pymoc.modules import Column`.

Let me know if you have any luck with this update, and if so I can close this out!

**Comment by mbueti** [comment]
We should be 100% up and running, with both `from pymoc.modules import Column` for `Column(...)` and `import pymoc` for `pymoc.modules.Column(...)`

**Comment by MFJansen** [comment]
Install is now working for me. Oddly enough I still don't have any luck with development mode though (on neither of the two machines that I tried on). Not sure why that is...

**Comment by mbueti** [comment]
Very odd...I’ll look at developer mode this evening.

Mike Bueti

**Comment by mbueti** [comment]
Okay, I've tracked down the problem! It seems there's a longstanding issue with setuptools (open for more than five years) that prevents develop mode from linking properly when the src directory does not exactly share the package name https://github.com/pypa/setuptools/issues/230

The workaround here was to revert the directory structure so that the source lives in a pymoc directory within `src`, and the `setup.py` script maps the packages there. 

Develop and normal install should now be 100% working, sorry for the odd behavior there!

**Comment by MFJansen** [comment]
And I see you also fixed all the module imports in the examples, which I was literally working on just now... Great!

**Comment by mbueti** [comment]
Yup! It was low hanging fruit while I was in fixing the tests!

And the added benefit is that this looks like it was the same bug blocking publication, so I have a "release candidate" registered on pypi at https://pypi.org/project/py-moc/, which means users can now install using pip! Unfortunately, `pymoc` was already registered by somebody for an astronomy package, but once users have run `pip install py-moc` they can just `import pymoc` or pull in the modules as usual.

**Comment by MFJansen** [comment]
One more issue I just noticed is that the plotting tools are not being installed right now. If you get a chance to add that, that would be great! Otherwise I'll try to do it at some point (not tonight...)

**Comment by mbueti** [comment]
@MFJansen `import pymoc.plotting` and all of its various permutations should be working again! Give it a try, and if it works for you I'll close this ticket out

**Comment by MFJansen** [comment]
Looks good! Thanks! I'll close this issue.
