### ISSUE TITLE
Python 2 support?

### ISSUE THREAD

**Issue by MFJansen** [pymoc/pymoc_old#3]
The setup script suggests that the model requires python 3. In practice, I don't seem to have a problem using it with python 2.7 (except for some reason again when installing in developer mode in which case I got a complaint about NON-ASCII characters in psi_SO.py). Is there any reason why we would want to give up compatibility with python 2? (In my experience 2.7 is still used pretty widely - e.g. it's the default on our university cluster.)

**Comment by mbueti** [comment]
Good catch! I'd had a requirement in there for python3 previously that I removed, but hadn't removed it from the classifier.

What I'd like to do, before removing that, is to get automated testing working in 2.7. I should be able to create an alternate build environment and have Circle run the tests in parallel. My only concern is that since my environment is 3.7, it would be easy to slip in a breaking change in 2.x without noticing. That should be straightforward though, and can get it done this week!

**Comment by mbueti** [comment]
okay, we have some minor updates to the code and tests, and testing happening in both Python 3.6 and 2.7, which you can see here https://circleci.com/workflow-run/ee270d56-c698-4913-a6a7-902897477802

I'm pretty well comfortable publishing that both platforms are supported, now that they're covered
